os: linux

language: bash

services:
- docker

branches:
  only:
    - master
    - /^\d+\.\d+\.\d+$/

before_install:
- docker build -t cnf .
- curl -L https://goss.rocks/install | sudo sh

script: dgoss run cnf sleep 3

after_success: 
- ./docker.sh
