---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cnf-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: chuck.aws2.velero.lan
    http:
      paths:
      - path: "/"
        backend:
          serviceName: cnf-service
          servicePort: 80
