apiVersion: v1
kind: Service
metadata:
  name: cnf-metrics
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/scheme: 'http'
    prometheus.io/path: '/metrics'
spec:
  clusterIP: ""
  ports:
  - name: metrics
    port: 9121
    protocol: TCP
    targetPort: 9000
  selector:
    app: chuck-norris-facts
  type: ClusterIP
